# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1170, 896)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        Mainwindow.setFont(font)
        Mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_22.addWidget(self.label_7)
        self.tabWiget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWiget.setObjectName("tabWiget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.ptGenUrlMovie = QtWidgets.QLineEdit(parent=self.tab)
        self.ptGenUrlMovie.setText("")
        self.ptGenUrlMovie.setClearButtonEnabled(True)
        self.ptGenUrlMovie.setObjectName("ptGenUrlMovie")
        self.verticalLayout_7.addWidget(self.ptGenUrlMovie)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.sourceMovie = QtWidgets.QComboBox(parent=self.tab)
        self.sourceMovie.setEditable(True)
        self.sourceMovie.setObjectName("sourceMovie")
        self.horizontalLayout_5.addWidget(self.sourceMovie)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.teamMovie = QtWidgets.QComboBox(parent=self.tab)
        self.teamMovie.setEditable(True)
        self.teamMovie.setObjectName("teamMovie")
        self.horizontalLayout_6.addWidget(self.teamMovie)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.videoPathMovie = QtWidgets.QLineEdit(parent=self.tab)
        self.videoPathMovie.setText("")
        self.videoPathMovie.setDragEnabled(True)
        self.videoPathMovie.setClearButtonEnabled(True)
        self.videoPathMovie.setObjectName("videoPathMovie")
        self.horizontalLayout.addWidget(self.videoPathMovie)
        self.selectVideoButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.selectVideoButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoButtonMovie.setObjectName("selectVideoButtonMovie")
        self.horizontalLayout.addWidget(self.selectVideoButtonMovie)
        self.selectVideoFolderButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.selectVideoFolderButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoFolderButtonMovie.setObjectName("selectVideoFolderButtonMovie")
        self.horizontalLayout.addWidget(self.selectVideoFolderButtonMovie)
        self.makeTorrentButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.makeTorrentButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.makeTorrentButtonMovie.setObjectName("makeTorrentButtonMovie")
        self.horizontalLayout.addWidget(self.makeTorrentButtonMovie)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.ptGenBrowserMovie = QtWidgets.QTextEdit(parent=self.tab)
        self.ptGenBrowserMovie.setObjectName("ptGenBrowserMovie")
        self.verticalLayout.addWidget(self.ptGenBrowserMovie)
        self.getPtGenButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.getPtGenButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPtGenButtonMovie.setObjectName("getPtGenButtonMovie")
        self.verticalLayout.addWidget(self.getPtGenButtonMovie)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.pictureUrlBrowserMovie = QtWidgets.QTextEdit(parent=self.tab)
        self.pictureUrlBrowserMovie.setObjectName("pictureUrlBrowserMovie")
        self.verticalLayout_2.addWidget(self.pictureUrlBrowserMovie)
        self.getPictureButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.getPictureButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPictureButtonMovie.setObjectName("getPictureButtonMovie")
        self.verticalLayout_2.addWidget(self.getPictureButtonMovie)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.debugBrowserMovie = QtWidgets.QTextBrowser(parent=self.tab)
        self.debugBrowserMovie.setObjectName("debugBrowserMovie")
        self.verticalLayout_3.addWidget(self.debugBrowserMovie)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.label_12 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.mainTitleBrowserMovie = QtWidgets.QTextEdit(parent=self.tab)
        self.mainTitleBrowserMovie.setObjectName("mainTitleBrowserMovie")
        self.horizontalLayout_3.addWidget(self.mainTitleBrowserMovie)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.secondTitleBrowserMovie = QtWidgets.QTextEdit(parent=self.tab)
        self.secondTitleBrowserMovie.setObjectName("secondTitleBrowserMovie")
        self.horizontalLayout_7.addWidget(self.secondTitleBrowserMovie)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.fileNameBrowserMovie = QtWidgets.QTextEdit(parent=self.tab)
        self.fileNameBrowserMovie.setObjectName("fileNameBrowserMovie")
        self.horizontalLayout_8.addWidget(self.fileNameBrowserMovie)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.getNameButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.getNameButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getNameButtonMovie.setObjectName("getNameButtonMovie")
        self.verticalLayout_5.addWidget(self.getNameButtonMovie)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.mediainfoBrowserMovie = QtWidgets.QTextBrowser(parent=self.tab)
        self.mediainfoBrowserMovie.setObjectName("mediainfoBrowserMovie")
        self.verticalLayout_4.addWidget(self.mediainfoBrowserMovie)
        self.getMediaInfoButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.getMediaInfoButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getMediaInfoButtonMovie.setObjectName("getMediaInfoButtonMovie")
        self.verticalLayout_4.addWidget(self.getMediaInfoButtonMovie)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.startButtonMovie.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.startButtonMovie.setFont(font)
        self.startButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.startButtonMovie.setObjectName("startButtonMovie")
        self.horizontalLayout_9.addWidget(self.startButtonMovie)
        self.autoFeedButtonMovie = QtWidgets.QPushButton(parent=self.tab)
        self.autoFeedButtonMovie.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.autoFeedButtonMovie.setFont(font)
        self.autoFeedButtonMovie.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.autoFeedButtonMovie.setObjectName("autoFeedButtonMovie")
        self.horizontalLayout_9.addWidget(self.autoFeedButtonMovie)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.tabWiget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_45 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_33.addWidget(self.label_45)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_46 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_34.addWidget(self.label_46)
        self.verticalLayout_11.addLayout(self.verticalLayout_34)
        self.ptGenUrlTV = QtWidgets.QLineEdit(parent=self.tab_2)
        self.ptGenUrlTV.setText("")
        self.ptGenUrlTV.setClearButtonEnabled(True)
        self.ptGenUrlTV.setObjectName("ptGenUrlTV")
        self.verticalLayout_11.addWidget(self.ptGenUrlTV)
        self.verticalLayout_24.addLayout(self.verticalLayout_11)
        self.horizontalLayout_31.addLayout(self.verticalLayout_24)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_58 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_39.addWidget(self.label_58)
        self.verticalLayout_42.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.seasonBoxTV = QtWidgets.QSpinBox(parent=self.tab_2)
        self.seasonBoxTV.setMinimum(1)
        self.seasonBoxTV.setObjectName("seasonBoxTV")
        self.horizontalLayout_40.addWidget(self.seasonBoxTV)
        self.verticalLayout_42.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_31.addLayout(self.verticalLayout_42)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_60 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_43.addWidget(self.label_60)
        self.verticalLayout_44.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.episodeStartBoxTV = QtWidgets.QSpinBox(parent=self.tab_2)
        self.episodeStartBoxTV.setMinimum(1)
        self.episodeStartBoxTV.setMaximum(9999)
        self.episodeStartBoxTV.setObjectName("episodeStartBoxTV")
        self.horizontalLayout_44.addWidget(self.episodeStartBoxTV)
        self.label_61 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_44.addWidget(self.label_61)
        self.verticalLayout_44.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_31.addLayout(self.verticalLayout_44)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_47 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_32.addWidget(self.label_47)
        self.sourceTV = QtWidgets.QComboBox(parent=self.tab_2)
        self.sourceTV.setEditable(True)
        self.sourceTV.setObjectName("sourceTV")
        self.horizontalLayout_32.addWidget(self.sourceTV)
        self.verticalLayout_35.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_48 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_33.addWidget(self.label_48)
        self.teamTV = QtWidgets.QComboBox(parent=self.tab_2)
        self.teamTV.setEditable(True)
        self.teamTV.setObjectName("teamTV")
        self.horizontalLayout_33.addWidget(self.teamTV)
        self.verticalLayout_35.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_31.addLayout(self.verticalLayout_35)
        self.verticalLayout_33.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_49 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_34.addWidget(self.label_49)
        self.videoPathTV = QtWidgets.QLineEdit(parent=self.tab_2)
        self.videoPathTV.setText("")
        self.videoPathTV.setDragEnabled(True)
        self.videoPathTV.setClearButtonEnabled(True)
        self.videoPathTV.setObjectName("videoPathTV")
        self.horizontalLayout_34.addWidget(self.videoPathTV)
        self.selectVideoFolderButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.selectVideoFolderButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoFolderButtonTV.setObjectName("selectVideoFolderButtonTV")
        self.horizontalLayout_34.addWidget(self.selectVideoFolderButtonTV)
        self.makeTorrentButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.makeTorrentButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.makeTorrentButtonTV.setObjectName("makeTorrentButtonTV")
        self.horizontalLayout_34.addWidget(self.makeTorrentButtonTV)
        self.verticalLayout_33.addLayout(self.horizontalLayout_34)
        self.verticalLayout_32.addLayout(self.verticalLayout_33)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_50 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_36.addWidget(self.label_50)
        self.ptGenBrowserTV = QtWidgets.QTextEdit(parent=self.tab_2)
        self.ptGenBrowserTV.setObjectName("ptGenBrowserTV")
        self.verticalLayout_36.addWidget(self.ptGenBrowserTV)
        self.getPtGenButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.getPtGenButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPtGenButtonTV.setObjectName("getPtGenButtonTV")
        self.verticalLayout_36.addWidget(self.getPtGenButtonTV)
        self.verticalLayout_32.addLayout(self.verticalLayout_36)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_51 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_37.addWidget(self.label_51)
        self.pictureUrlBrowserTV = QtWidgets.QTextEdit(parent=self.tab_2)
        self.pictureUrlBrowserTV.setObjectName("pictureUrlBrowserTV")
        self.verticalLayout_37.addWidget(self.pictureUrlBrowserTV)
        self.getPictureButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.getPictureButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPictureButtonTV.setObjectName("getPictureButtonTV")
        self.verticalLayout_37.addWidget(self.getPictureButtonTV)
        self.verticalLayout_32.addLayout(self.verticalLayout_37)
        self.horizontalLayout_30.addLayout(self.verticalLayout_32)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_52 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_39.addWidget(self.label_52)
        self.debugBrowserTV = QtWidgets.QTextBrowser(parent=self.tab_2)
        self.debugBrowserTV.setObjectName("debugBrowserTV")
        self.verticalLayout_39.addWidget(self.debugBrowserTV)
        self.verticalLayout_38.addLayout(self.verticalLayout_39)
        self.label_53 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_38.addWidget(self.label_53)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_54 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_35.addWidget(self.label_54)
        self.mainTitleBrowserTV = QtWidgets.QTextEdit(parent=self.tab_2)
        self.mainTitleBrowserTV.setObjectName("mainTitleBrowserTV")
        self.horizontalLayout_35.addWidget(self.mainTitleBrowserTV)
        self.verticalLayout_38.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_55 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_36.addWidget(self.label_55)
        self.secondTitleBrowserTV = QtWidgets.QTextEdit(parent=self.tab_2)
        self.secondTitleBrowserTV.setObjectName("secondTitleBrowserTV")
        self.horizontalLayout_36.addWidget(self.secondTitleBrowserTV)
        self.verticalLayout_38.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_56 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_37.addWidget(self.label_56)
        self.fileNameBrowserTV = QtWidgets.QTextEdit(parent=self.tab_2)
        self.fileNameBrowserTV.setObjectName("fileNameBrowserTV")
        self.horizontalLayout_37.addWidget(self.fileNameBrowserTV)
        self.verticalLayout_38.addLayout(self.horizontalLayout_37)
        self.getNameButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.getNameButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getNameButtonTV.setObjectName("getNameButtonTV")
        self.verticalLayout_38.addWidget(self.getNameButtonTV)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_57 = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_40.addWidget(self.label_57)
        self.mediainfoBrowserTV = QtWidgets.QTextBrowser(parent=self.tab_2)
        self.mediainfoBrowserTV.setObjectName("mediainfoBrowserTV")
        self.verticalLayout_40.addWidget(self.mediainfoBrowserTV)
        self.getMediaInfoButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.getMediaInfoButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getMediaInfoButtonTV.setObjectName("getMediaInfoButtonTV")
        self.verticalLayout_40.addWidget(self.getMediaInfoButtonTV)
        self.verticalLayout_38.addLayout(self.verticalLayout_40)
        self.horizontalLayout_30.addLayout(self.verticalLayout_38)
        self.verticalLayout_31.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.startButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.startButtonTV.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.startButtonTV.setFont(font)
        self.startButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.startButtonTV.setObjectName("startButtonTV")
        self.horizontalLayout_38.addWidget(self.startButtonTV)
        self.autoFeedButtonTV = QtWidgets.QPushButton(parent=self.tab_2)
        self.autoFeedButtonTV.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.autoFeedButtonTV.setFont(font)
        self.autoFeedButtonTV.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.autoFeedButtonTV.setObjectName("autoFeedButtonTV")
        self.horizontalLayout_38.addWidget(self.autoFeedButtonTV)
        self.verticalLayout_31.addLayout(self.horizontalLayout_38)
        self.verticalLayout_41.addLayout(self.verticalLayout_31)
        self.tabWiget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_15.addWidget(self.label_17)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.originalNameEditPlaylet = QtWidgets.QLineEdit(parent=self.tab_3)
        self.originalNameEditPlaylet.setObjectName("originalNameEditPlaylet")
        self.horizontalLayout_11.addWidget(self.originalNameEditPlaylet)
        self.label_9 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.yearEditPlaylet = QtWidgets.QLineEdit(parent=self.tab_3)
        self.yearEditPlaylet.setMaxLength(10)
        self.yearEditPlaylet.setObjectName("yearEditPlaylet")
        self.horizontalLayout_11.addWidget(self.yearEditPlaylet)
        self.label_18 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.seasonBoxPlaylet = QtWidgets.QSpinBox(parent=self.tab_3)
        self.seasonBoxPlaylet.setMinimum(1)
        self.seasonBoxPlaylet.setObjectName("seasonBoxPlaylet")
        self.horizontalLayout_11.addWidget(self.seasonBoxPlaylet)
        self.label_62 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_11.addWidget(self.label_62)
        self.episodeStartBoxPlaylet = QtWidgets.QSpinBox(parent=self.tab_3)
        self.episodeStartBoxPlaylet.setMinimum(1)
        self.episodeStartBoxPlaylet.setMaximum(9999)
        self.episodeStartBoxPlaylet.setObjectName("episodeStartBoxPlaylet")
        self.horizontalLayout_11.addWidget(self.episodeStartBoxPlaylet)
        self.label_63 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_11.addWidget(self.label_63)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.typePlaylet = QtWidgets.QComboBox(parent=self.tab_3)
        self.typePlaylet.setEditable(True)
        self.typePlaylet.setObjectName("typePlaylet")
        self.horizontalLayout_12.addWidget(self.typePlaylet)
        self.label_33 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.areaPlaylet = QtWidgets.QComboBox(parent=self.tab_3)
        self.areaPlaylet.setEditable(True)
        self.areaPlaylet.setObjectName("areaPlaylet")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.addItem("")
        self.areaPlaylet.setItemText(6, "")
        self.horizontalLayout_12.addWidget(self.areaPlaylet)
        self.label_32 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_12.addWidget(self.label_32)
        self.languagePlaylet = QtWidgets.QComboBox(parent=self.tab_3)
        self.languagePlaylet.setEditable(True)
        self.languagePlaylet.setObjectName("languagePlaylet")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.addItem("")
        self.languagePlaylet.setItemText(7, "")
        self.horizontalLayout_12.addWidget(self.languagePlaylet)
        self.label_20 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.sourcePlaylet = QtWidgets.QComboBox(parent=self.tab_3)
        self.sourcePlaylet.setEditable(True)
        self.sourcePlaylet.setObjectName("sourcePlaylet")
        self.horizontalLayout_12.addWidget(self.sourcePlaylet)
        self.label_21 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.teamPlaylet = QtWidgets.QComboBox(parent=self.tab_3)
        self.teamPlaylet.setEditable(True)
        self.teamPlaylet.setObjectName("teamPlaylet")
        self.horizontalLayout_12.addWidget(self.teamPlaylet)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.videoPathPlaylet = QtWidgets.QLineEdit(parent=self.tab_3)
        self.videoPathPlaylet.setText("")
        self.videoPathPlaylet.setDragEnabled(True)
        self.videoPathPlaylet.setClearButtonEnabled(True)
        self.videoPathPlaylet.setObjectName("videoPathPlaylet")
        self.horizontalLayout_13.addWidget(self.videoPathPlaylet)
        self.selectVideoFolderButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.selectVideoFolderButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoFolderButtonPlaylet.setObjectName("selectVideoFolderButtonPlaylet")
        self.horizontalLayout_13.addWidget(self.selectVideoFolderButtonPlaylet)
        self.makeTorrentButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.makeTorrentButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.makeTorrentButtonPlaylet.setObjectName("makeTorrentButtonPlaylet")
        self.horizontalLayout_13.addWidget(self.makeTorrentButtonPlaylet)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_23 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.coverPathPlaylet = QtWidgets.QLineEdit(parent=self.tab_3)
        self.coverPathPlaylet.setText("")
        self.coverPathPlaylet.setDragEnabled(True)
        self.coverPathPlaylet.setClearButtonEnabled(True)
        self.coverPathPlaylet.setObjectName("coverPathPlaylet")
        self.horizontalLayout_14.addWidget(self.coverPathPlaylet)
        self.selectCoverFolderButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.selectCoverFolderButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectCoverFolderButtonPlaylet.setObjectName("selectCoverFolderButtonPlaylet")
        self.horizontalLayout_14.addWidget(self.selectCoverFolderButtonPlaylet)
        self.uploadCoverButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.uploadCoverButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.uploadCoverButtonPlaylet.setObjectName("uploadCoverButtonPlaylet")
        self.horizontalLayout_14.addWidget(self.uploadCoverButtonPlaylet)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBox_0 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_0.setObjectName("checkBox_0")
        self.horizontalLayout_15.addWidget(self.checkBox_0)
        self.checkBox_1 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout_15.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_15.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_15.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_15.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_15.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_15.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_15.addWidget(self.checkBox_7)
        self.verticalLayout_15.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_16.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_16.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_16.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_16.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_16.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_16.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_16.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(parent=self.tab_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_16.addWidget(self.checkBox_15)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_14.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_24 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_16.addWidget(self.label_24)
        self.descriptionBrowserPlaylet = QtWidgets.QTextEdit(parent=self.tab_3)
        self.descriptionBrowserPlaylet.setObjectName("descriptionBrowserPlaylet")
        self.verticalLayout_16.addWidget(self.descriptionBrowserPlaylet)
        self.getDescriptionButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.getDescriptionButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getDescriptionButtonPlaylet.setObjectName("getDescriptionButtonPlaylet")
        self.verticalLayout_16.addWidget(self.getDescriptionButtonPlaylet)
        self.verticalLayout_14.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.pictureUrlBrowserPlaylet = QtWidgets.QTextEdit(parent=self.tab_3)
        self.pictureUrlBrowserPlaylet.setObjectName("pictureUrlBrowserPlaylet")
        self.verticalLayout_17.addWidget(self.pictureUrlBrowserPlaylet)
        self.getPictureButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.getPictureButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPictureButtonPlaylet.setObjectName("getPictureButtonPlaylet")
        self.verticalLayout_17.addWidget(self.getPictureButtonPlaylet)
        self.verticalLayout_14.addLayout(self.verticalLayout_17)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_26 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_19.addWidget(self.label_26)
        self.debugBrowserPlaylet = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.debugBrowserPlaylet.setObjectName("debugBrowserPlaylet")
        self.verticalLayout_19.addWidget(self.debugBrowserPlaylet)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.label_27 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_18.addWidget(self.label_27)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_28 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_17.addWidget(self.label_28)
        self.mainTitleBrowserPlaylet = QtWidgets.QTextEdit(parent=self.tab_3)
        self.mainTitleBrowserPlaylet.setObjectName("mainTitleBrowserPlaylet")
        self.horizontalLayout_17.addWidget(self.mainTitleBrowserPlaylet)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_29 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.secondTitleBrowserPlaylet = QtWidgets.QTextEdit(parent=self.tab_3)
        self.secondTitleBrowserPlaylet.setObjectName("secondTitleBrowserPlaylet")
        self.horizontalLayout_18.addWidget(self.secondTitleBrowserPlaylet)
        self.verticalLayout_18.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_30 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.fileNameBrowserPlaylet = QtWidgets.QTextEdit(parent=self.tab_3)
        self.fileNameBrowserPlaylet.setObjectName("fileNameBrowserPlaylet")
        self.horizontalLayout_19.addWidget(self.fileNameBrowserPlaylet)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        self.getNameButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.getNameButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getNameButtonPlaylet.setObjectName("getNameButtonPlaylet")
        self.verticalLayout_18.addWidget(self.getNameButtonPlaylet)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_31 = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_20.addWidget(self.label_31)
        self.mediainfoBrowserPlaylet = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.mediainfoBrowserPlaylet.setObjectName("mediainfoBrowserPlaylet")
        self.verticalLayout_20.addWidget(self.mediainfoBrowserPlaylet)
        self.getMediaInfoButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.getMediaInfoButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getMediaInfoButtonPlaylet.setObjectName("getMediaInfoButtonPlaylet")
        self.verticalLayout_20.addWidget(self.getMediaInfoButtonPlaylet)
        self.verticalLayout_18.addLayout(self.verticalLayout_20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_18)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.startButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.startButtonPlaylet.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.startButtonPlaylet.setFont(font)
        self.startButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.startButtonPlaylet.setObjectName("startButtonPlaylet")
        self.horizontalLayout_20.addWidget(self.startButtonPlaylet)
        self.autoFeedButtonPlaylet = QtWidgets.QPushButton(parent=self.tab_3)
        self.autoFeedButtonPlaylet.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.autoFeedButtonPlaylet.setFont(font)
        self.autoFeedButtonPlaylet.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.autoFeedButtonPlaylet.setObjectName("autoFeedButtonPlaylet")
        self.horizontalLayout_20.addWidget(self.autoFeedButtonPlaylet)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.verticalLayout_21.addLayout(self.verticalLayout_13)
        self.tabWiget.addTab(self.tab_3, "")
        self.verticalLayout_22.addWidget(self.tabWiget)
        Mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        Mainwindow.setMenuBar(self.menubar)
        self.actionsettings = QtGui.QAction(parent=Mainwindow)
        self.actionsettings.setObjectName("actionsettings")
        self.actiongit = QtGui.QAction(parent=Mainwindow)
        self.actiongit.setObjectName("actiongit")
        self.menu.addAction(self.actionsettings)
        self.menu.addAction(self.actiongit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mainwindow)
        self.tabWiget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "ph-bjd"))
        self.label_7.setText(_translate("Mainwindow", "Publish Helper"))
        self.label_16.setText(_translate("Mainwindow", "输入"))
        self.label.setText(_translate("Mainwindow", "输入豆瓣、IMDb等资源链接:"))
        self.label_3.setText(_translate("Mainwindow", "来源:"))
        self.label_6.setText(_translate("Mainwindow", "小组:"))
        self.label_2.setText(_translate("Mainwindow", "资源路径:"))
        self.selectVideoButtonMovie.setText(_translate("Mainwindow", "文件"))
        self.selectVideoFolderButtonMovie.setText(_translate("Mainwindow", "文件夹"))
        self.makeTorrentButtonMovie.setText(_translate("Mainwindow", "制作种子"))
        self.label_11.setText(_translate("Mainwindow", "简介"))
        self.getPtGenButtonMovie.setText(_translate("Mainwindow", "获取"))
        self.label_5.setText(_translate("Mainwindow", "截图"))
        self.getPictureButtonMovie.setText(_translate("Mainwindow", "获取"))
        self.label_4.setText(_translate("Mainwindow", "Debug窗口"))
        self.label_12.setText(_translate("Mainwindow", "命名"))
        self.label_13.setText(_translate("Mainwindow", "主标题:"))
        self.label_14.setText(_translate("Mainwindow", "副标题:"))
        self.label_15.setText(_translate("Mainwindow", "文件名:"))
        self.getNameButtonMovie.setText(_translate("Mainwindow", "获取标准命名"))
        self.label_10.setText(_translate("Mainwindow", "MediaInfo"))
        self.getMediaInfoButtonMovie.setText(_translate("Mainwindow", "获取"))
        self.startButtonMovie.setText(_translate("Mainwindow", "万事俱备，一键启动！"))
        self.autoFeedButtonMovie.setText(_translate("Mainwindow", "将当前信息生成auto feed链接"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab), _translate("Mainwindow", "电影"))
        self.label_45.setText(_translate("Mainwindow", "输入"))
        self.label_46.setText(_translate("Mainwindow", "输入豆瓣、IMDb等资源链接:"))
        self.label_58.setText(_translate("Mainwindow", "季数:"))
        self.label_60.setText(_translate("Mainwindow", "开始于:"))
        self.label_61.setText(_translate("Mainwindow", "集"))
        self.label_47.setText(_translate("Mainwindow", "来源:"))
        self.label_48.setText(_translate("Mainwindow", "小组:"))
        self.label_49.setText(_translate("Mainwindow", "资源路径:"))
        self.selectVideoFolderButtonTV.setText(_translate("Mainwindow", "文件夹"))
        self.makeTorrentButtonTV.setText(_translate("Mainwindow", "制作种子"))
        self.label_50.setText(_translate("Mainwindow", "简介"))
        self.getPtGenButtonTV.setText(_translate("Mainwindow", "获取"))
        self.label_51.setText(_translate("Mainwindow", "截图"))
        self.getPictureButtonTV.setText(_translate("Mainwindow", "获取"))
        self.label_52.setText(_translate("Mainwindow", "Debug窗口"))
        self.label_53.setText(_translate("Mainwindow", "命名"))
        self.label_54.setText(_translate("Mainwindow", "主标题:"))
        self.label_55.setText(_translate("Mainwindow", "副标题:"))
        self.label_56.setText(_translate("Mainwindow", "文件名:"))
        self.getNameButtonTV.setText(_translate("Mainwindow", "获取标准命名"))
        self.label_57.setText(_translate("Mainwindow", "MediaInfo"))
        self.getMediaInfoButtonTV.setText(_translate("Mainwindow", "获取"))
        self.startButtonTV.setText(_translate("Mainwindow", "万事俱备，一键启动！"))
        self.autoFeedButtonTV.setText(_translate("Mainwindow", "将当前信息生成auto feed链接"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab_2), _translate("Mainwindow", "剧集"))
        self.label_17.setText(_translate("Mainwindow", "输入"))
        self.label_8.setText(_translate("Mainwindow", "资源名称:"))
        self.label_9.setText(_translate("Mainwindow", "发布年份:"))
        self.label_18.setText(_translate("Mainwindow", "季数:"))
        self.label_62.setText(_translate("Mainwindow", "开始于:"))
        self.label_63.setText(_translate("Mainwindow", "集"))
        self.label_19.setText(_translate("Mainwindow", "类型:"))
        self.label_33.setText(_translate("Mainwindow", "产地:"))
        self.areaPlaylet.setItemText(0, _translate("Mainwindow", "大陆"))
        self.areaPlaylet.setItemText(1, _translate("Mainwindow", "港台"))
        self.areaPlaylet.setItemText(2, _translate("Mainwindow", "欧美"))
        self.areaPlaylet.setItemText(3, _translate("Mainwindow", "日本"))
        self.areaPlaylet.setItemText(4, _translate("Mainwindow", "韩国"))
        self.areaPlaylet.setItemText(5, _translate("Mainwindow", "印度"))
        self.label_32.setText(_translate("Mainwindow", "语言:"))
        self.languagePlaylet.setItemText(0, _translate("Mainwindow", "国语"))
        self.languagePlaylet.setItemText(1, _translate("Mainwindow", "粤语"))
        self.languagePlaylet.setItemText(2, _translate("Mainwindow", "英语"))
        self.languagePlaylet.setItemText(3, _translate("Mainwindow", "法语"))
        self.languagePlaylet.setItemText(4, _translate("Mainwindow", "德语"))
        self.languagePlaylet.setItemText(5, _translate("Mainwindow", "韩语"))
        self.languagePlaylet.setItemText(6, _translate("Mainwindow", "日语"))
        self.label_20.setText(_translate("Mainwindow", "来源:"))
        self.label_21.setText(_translate("Mainwindow", "小组:"))
        self.label_22.setText(_translate("Mainwindow", "资源路径:"))
        self.selectVideoFolderButtonPlaylet.setText(_translate("Mainwindow", "文件夹"))
        self.makeTorrentButtonPlaylet.setText(_translate("Mainwindow", "制作种子"))
        self.label_23.setText(_translate("Mainwindow", "封面路径:"))
        self.selectCoverFolderButtonPlaylet.setText(_translate("Mainwindow", "浏览"))
        self.uploadCoverButtonPlaylet.setText(_translate("Mainwindow", "上传"))
        self.checkBox_0.setText(_translate("Mainwindow", "剧情"))
        self.checkBox_1.setText(_translate("Mainwindow", "爱情"))
        self.checkBox_2.setText(_translate("Mainwindow", "喜剧"))
        self.checkBox_3.setText(_translate("Mainwindow", "甜虐"))
        self.checkBox_4.setText(_translate("Mainwindow", "甜宠"))
        self.checkBox_5.setText(_translate("Mainwindow", "恐怖"))
        self.checkBox_6.setText(_translate("Mainwindow", "动作"))
        self.checkBox_7.setText(_translate("Mainwindow", "穿越"))
        self.checkBox_8.setText(_translate("Mainwindow", "重生"))
        self.checkBox_9.setText(_translate("Mainwindow", "逆袭"))
        self.checkBox_10.setText(_translate("Mainwindow", "科幻"))
        self.checkBox_11.setText(_translate("Mainwindow", "武侠"))
        self.checkBox_12.setText(_translate("Mainwindow", "都市"))
        self.checkBox_13.setText(_translate("Mainwindow", "古装"))
        self.checkBox_14.setText(_translate("Mainwindow", "神豪"))
        self.checkBox_15.setText(_translate("Mainwindow", "霸总"))
        self.label_24.setText(_translate("Mainwindow", "简介"))
        self.getDescriptionButtonPlaylet.setText(_translate("Mainwindow", "获取"))
        self.label_25.setText(_translate("Mainwindow", "截图"))
        self.getPictureButtonPlaylet.setText(_translate("Mainwindow", "获取"))
        self.label_26.setText(_translate("Mainwindow", "Debug窗口"))
        self.label_27.setText(_translate("Mainwindow", "命名"))
        self.label_28.setText(_translate("Mainwindow", "主标题:"))
        self.label_29.setText(_translate("Mainwindow", "副标题:"))
        self.label_30.setText(_translate("Mainwindow", "文件名:"))
        self.getNameButtonPlaylet.setText(_translate("Mainwindow", "获取标准命名"))
        self.label_31.setText(_translate("Mainwindow", "MediaInfo"))
        self.getMediaInfoButtonPlaylet.setText(_translate("Mainwindow", "获取"))
        self.startButtonPlaylet.setText(_translate("Mainwindow", "万事俱备，一键启动！"))
        self.autoFeedButtonPlaylet.setText(_translate("Mainwindow", "将当前信息生成auto feed链接"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.tab_3), _translate("Mainwindow", "短剧"))
        self.menu.setTitle(_translate("Mainwindow", "工具"))
        self.actionsettings.setText(_translate("Mainwindow", "设置"))
        self.actiongit.setText(_translate("Mainwindow", "项目仓库"))
