# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(1170, 896)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        Mainwindow.setFont(font)
        Mainwindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(21)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.ptGenUrl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ptGenUrl.setText("")
        self.ptGenUrl.setClearButtonEnabled(True)
        self.ptGenUrl.setObjectName("ptGenUrl")
        self.verticalLayout_7.addWidget(self.ptGenUrl)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.source = QtWidgets.QComboBox(parent=self.centralwidget)
        self.source.setEditable(True)
        self.source.setObjectName("source")
        self.horizontalLayout_5.addWidget(self.source)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.team = QtWidgets.QComboBox(parent=self.centralwidget)
        self.team.setEditable(True)
        self.team.setObjectName("team")
        self.horizontalLayout_6.addWidget(self.team)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.videoPath = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.videoPath.setText("")
        self.videoPath.setDragEnabled(True)
        self.videoPath.setClearButtonEnabled(True)
        self.videoPath.setObjectName("videoPath")
        self.horizontalLayout.addWidget(self.videoPath)
        self.selectVideoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectVideoButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoButton.setObjectName("selectVideoButton")
        self.horizontalLayout.addWidget(self.selectVideoButton)
        self.selectVideoFolderButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.selectVideoFolderButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectVideoFolderButton.setObjectName("selectVideoFolderButton")
        self.horizontalLayout.addWidget(self.selectVideoFolderButton)
        self.makeTorrentButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.makeTorrentButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.makeTorrentButton.setObjectName("makeTorrentButton")
        self.horizontalLayout.addWidget(self.makeTorrentButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.ptGenBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.ptGenBrowser.setObjectName("ptGenBrowser")
        self.verticalLayout.addWidget(self.ptGenBrowser)
        self.getPtGenButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPtGenButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPtGenButton.setObjectName("getPtGenButton")
        self.verticalLayout.addWidget(self.getPtGenButton)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.pictureUrlBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.pictureUrlBrowser.setObjectName("pictureUrlBrowser")
        self.verticalLayout_2.addWidget(self.pictureUrlBrowser)
        self.getPictureButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getPictureButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getPictureButton.setObjectName("getPictureButton")
        self.verticalLayout_2.addWidget(self.getPictureButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.debugBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.debugBrowser.setObjectName("debugBrowser")
        self.verticalLayout_3.addWidget(self.debugBrowser)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.mainTitleBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.mainTitleBrowser.setObjectName("mainTitleBrowser")
        self.horizontalLayout_3.addWidget(self.mainTitleBrowser)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.secondTitleBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.secondTitleBrowser.setObjectName("secondTitleBrowser")
        self.horizontalLayout_7.addWidget(self.secondTitleBrowser)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.fileNameBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.fileNameBrowser.setObjectName("fileNameBrowser")
        self.horizontalLayout_8.addWidget(self.fileNameBrowser)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.getNameButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getNameButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getNameButton.setObjectName("getNameButton")
        self.verticalLayout_5.addWidget(self.getNameButton)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.mediainfoBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.mediainfoBrowser.setObjectName("mediainfoBrowser")
        self.verticalLayout_4.addWidget(self.mediainfoBrowser)
        self.getMediaInfoButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.getMediaInfoButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.getMediaInfoButton.setObjectName("getMediaInfoButton")
        self.verticalLayout_4.addWidget(self.getMediaInfoButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 15px 25px;\n"
"    font-size: 24px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_9.addWidget(self.startButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        Mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Mainwindow)
        self.statusbar.setObjectName("statusbar")
        Mainwindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=Mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        Mainwindow.setMenuBar(self.menubar)
        self.actionsettings = QtGui.QAction(parent=Mainwindow)
        self.actionsettings.setObjectName("actionsettings")
        self.menu.addAction(self.actionsettings)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "ph-bjd"))
        self.label_7.setText(_translate("Mainwindow", "Publish Helper for Movie"))
        self.label_16.setText(_translate("Mainwindow", "输入"))
        self.label.setText(_translate("Mainwindow", "输入豆瓣号、Imdb号、豆瓣、IMDb等资源链接"))
        self.label_3.setText(_translate("Mainwindow", "来源："))
        self.label_6.setText(_translate("Mainwindow", "小组："))
        self.label_2.setText(_translate("Mainwindow", "资源路径："))
        self.selectVideoButton.setText(_translate("Mainwindow", "文件"))
        self.selectVideoFolderButton.setText(_translate("Mainwindow", "文件夹"))
        self.makeTorrentButton.setText(_translate("Mainwindow", "制作种子"))
        self.label_11.setText(_translate("Mainwindow", "简介"))
        self.getPtGenButton.setText(_translate("Mainwindow", "获取"))
        self.label_5.setText(_translate("Mainwindow", "截图"))
        self.getPictureButton.setText(_translate("Mainwindow", "获取"))
        self.label_4.setText(_translate("Mainwindow", "debug窗口"))
        self.label_12.setText(_translate("Mainwindow", "命名"))
        self.label_13.setText(_translate("Mainwindow", "主标题："))
        self.label_14.setText(_translate("Mainwindow", "副标题："))
        self.label_15.setText(_translate("Mainwindow", "文件名："))
        self.getNameButton.setText(_translate("Mainwindow", "获取标准命名"))
        self.label_10.setText(_translate("Mainwindow", "MediaInfo"))
        self.getMediaInfoButton.setText(_translate("Mainwindow", "获取"))
        self.startButton.setText(_translate("Mainwindow", "万事俱备，一键启动！"))
        self.menu.setTitle(_translate("Mainwindow", "工具"))
        self.actionsettings.setText(_translate("Mainwindow", "设置"))
