# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(646, 735)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget = QtWidgets.QTabWidget(parent=Settings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.ptGenApiUrl = QtWidgets.QLineEdit(parent=self.tab)
        self.ptGenApiUrl.setText("")
        self.ptGenApiUrl.setClearButtonEnabled(True)
        self.ptGenApiUrl.setObjectName("ptGenApiUrl")
        self.horizontalLayout_6.addWidget(self.ptGenApiUrl)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.pictureBedApiUrl = QtWidgets.QLineEdit(parent=self.tab)
        self.pictureBedApiUrl.setText("")
        self.pictureBedApiUrl.setClearButtonEnabled(True)
        self.pictureBedApiUrl.setObjectName("pictureBedApiUrl")
        self.horizontalLayout_4.addWidget(self.pictureBedApiUrl)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.pictureBedApiToken = QtWidgets.QLineEdit(parent=self.tab)
        self.pictureBedApiToken.setText("")
        self.pictureBedApiToken.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pictureBedApiToken.setClearButtonEnabled(True)
        self.pictureBedApiToken.setObjectName("pictureBedApiToken")
        self.horizontalLayout_5.addWidget(self.pictureBedApiToken)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.screenshotPath = QtWidgets.QLineEdit(parent=self.tab)
        self.screenshotPath.setText("")
        self.screenshotPath.setClearButtonEnabled(True)
        self.screenshotPath.setObjectName("screenshotPath")
        self.horizontalLayout_2.addWidget(self.screenshotPath)
        self.selectScreenshotPathButton = QtWidgets.QPushButton(parent=self.tab)
        self.selectScreenshotPathButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectScreenshotPathButton.setObjectName("selectScreenshotPathButton")
        self.horizontalLayout_2.addWidget(self.selectScreenshotPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(parent=self.tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.torrentPath = QtWidgets.QLineEdit(parent=self.tab)
        self.torrentPath.setText("")
        self.torrentPath.setClearButtonEnabled(True)
        self.torrentPath.setObjectName("torrentPath")
        self.horizontalLayout_3.addWidget(self.torrentPath)
        self.selectTorrentPathButton = QtWidgets.QPushButton(parent=self.tab)
        self.selectTorrentPathButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 3px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.selectTorrentPathButton.setObjectName("selectTorrentPathButton")
        self.horizontalLayout_3.addWidget(self.selectTorrentPathButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.screenshotNumber = QtWidgets.QSpinBox(parent=self.tab)
        self.screenshotNumber.setMaximum(5)
        self.screenshotNumber.setProperty("value", 1)
        self.screenshotNumber.setObjectName("screenshotNumber")
        self.horizontalLayout_7.addWidget(self.screenshotNumber)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.screenshotThreshold = QtWidgets.QDoubleSpinBox(parent=self.tab)
        self.screenshotThreshold.setDecimals(2)
        self.screenshotThreshold.setMaximum(50.0)
        self.screenshotThreshold.setSingleStep(0.01)
        self.screenshotThreshold.setProperty("value", 0.1)
        self.screenshotThreshold.setObjectName("screenshotThreshold")
        self.horizontalLayout_7.addWidget(self.screenshotThreshold)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.screenshotStartPercentage = QtWidgets.QDoubleSpinBox(parent=self.tab)
        self.screenshotStartPercentage.setDecimals(2)
        self.screenshotStartPercentage.setMaximum(1.0)
        self.screenshotStartPercentage.setSingleStep(0.01)
        self.screenshotStartPercentage.setProperty("value", 0.1)
        self.screenshotStartPercentage.setObjectName("screenshotStartPercentage")
        self.horizontalLayout_8.addWidget(self.screenshotStartPercentage)
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.screenshotEndPercentage = QtWidgets.QDoubleSpinBox(parent=self.tab)
        self.screenshotEndPercentage.setDecimals(2)
        self.screenshotEndPercentage.setMaximum(1.0)
        self.screenshotEndPercentage.setSingleStep(0.01)
        self.screenshotEndPercentage.setProperty("value", 0.9)
        self.screenshotEndPercentage.setObjectName("screenshotEndPercentage")
        self.horizontalLayout_8.addWidget(self.screenshotEndPercentage)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.autoUploadScreenshot = QtWidgets.QCheckBox(parent=self.tab)
        self.autoUploadScreenshot.setChecked(True)
        self.autoUploadScreenshot.setObjectName("autoUploadScreenshot")
        self.horizontalLayout_9.addWidget(self.autoUploadScreenshot)
        self.pasteScreenshotUrl = QtWidgets.QCheckBox(parent=self.tab)
        self.pasteScreenshotUrl.setChecked(True)
        self.pasteScreenshotUrl.setObjectName("pasteScreenshotUrl")
        self.horizontalLayout_9.addWidget(self.pasteScreenshotUrl)
        self.deleteScreenshot = QtWidgets.QCheckBox(parent=self.tab)
        self.deleteScreenshot.setChecked(True)
        self.deleteScreenshot.setObjectName("deleteScreenshot")
        self.horizontalLayout_9.addWidget(self.deleteScreenshot)
        self.mediaInfoSuffix = QtWidgets.QCheckBox(parent=self.tab)
        self.mediaInfoSuffix.setChecked(True)
        self.mediaInfoSuffix.setObjectName("mediaInfoSuffix")
        self.horizontalLayout_9.addWidget(self.mediaInfoSuffix)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.doGetThumbnail = QtWidgets.QCheckBox(parent=self.tab)
        self.doGetThumbnail.setObjectName("doGetThumbnail")
        self.horizontalLayout_11.addWidget(self.doGetThumbnail)
        self.label_13 = QtWidgets.QLabel(parent=self.tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.thumbnailRows = QtWidgets.QSpinBox(parent=self.tab)
        self.thumbnailRows.setMinimum(1)
        self.thumbnailRows.setMaximum(6)
        self.thumbnailRows.setProperty("value", 4)
        self.thumbnailRows.setObjectName("thumbnailRows")
        self.horizontalLayout_11.addWidget(self.thumbnailRows)
        self.label_14 = QtWidgets.QLabel(parent=self.tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.thumbnailCols = QtWidgets.QSpinBox(parent=self.tab)
        self.thumbnailCols.setMinimum(1)
        self.thumbnailCols.setMaximum(6)
        self.thumbnailCols.setProperty("value", 4)
        self.thumbnailCols.setObjectName("thumbnailCols")
        self.horizontalLayout_11.addWidget(self.thumbnailCols)
        self.label_31 = QtWidgets.QLabel(parent=self.tab)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_11.addWidget(self.label_31)
        self.thumbnailDelay = QtWidgets.QDoubleSpinBox(parent=self.tab)
        self.thumbnailDelay.setDecimals(1)
        self.thumbnailDelay.setMaximum(10.0)
        self.thumbnailDelay.setSingleStep(0.1)
        self.thumbnailDelay.setProperty("value", 2.0)
        self.thumbnailDelay.setObjectName("thumbnailDelay")
        self.horizontalLayout_11.addWidget(self.thumbnailDelay)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.renameFile = QtWidgets.QCheckBox(parent=self.tab)
        self.renameFile.setChecked(False)
        self.renameFile.setObjectName("renameFile")
        self.horizontalLayout_10.addWidget(self.renameFile)
        self.makeDir = QtWidgets.QCheckBox(parent=self.tab)
        self.makeDir.setChecked(False)
        self.makeDir.setObjectName("makeDir")
        self.horizontalLayout_10.addWidget(self.makeDir)
        self.secondConfirmFileName = QtWidgets.QCheckBox(parent=self.tab)
        self.secondConfirmFileName.setChecked(False)
        self.secondConfirmFileName.setObjectName("secondConfirmFileName")
        self.horizontalLayout_10.addWidget(self.secondConfirmFileName)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.enableApi = QtWidgets.QCheckBox(parent=self.tab)
        self.enableApi.setObjectName("enableApi")
        self.horizontalLayout_27.addWidget(self.enableApi)
        self.label_32 = QtWidgets.QLabel(parent=self.tab)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        self.apiPort = QtWidgets.QSpinBox(parent=self.tab)
        self.apiPort.setMinimum(1)
        self.apiPort.setMaximum(65535)
        self.apiPort.setProperty("value", 5372)
        self.apiPort.setObjectName("apiPort")
        self.horizontalLayout_27.addWidget(self.apiPort)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.label_9 = QtWidgets.QLabel(parent=self.tab)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.nameTabWidget = QtWidgets.QTabWidget(parent=self.tab_2)
        self.nameTabWidget.setObjectName("nameTabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.mainTitleMovie = QtWidgets.QLineEdit(parent=self.tab_3)
        self.mainTitleMovie.setObjectName("mainTitleMovie")
        self.horizontalLayout_12.addWidget(self.mainTitleMovie)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.secondTitleMovie = QtWidgets.QLineEdit(parent=self.tab_3)
        self.secondTitleMovie.setObjectName("secondTitleMovie")
        self.horizontalLayout_14.addWidget(self.secondTitleMovie)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.fileNameMovie = QtWidgets.QLineEdit(parent=self.tab_3)
        self.fileNameMovie.setObjectName("fileNameMovie")
        self.horizontalLayout_13.addWidget(self.fileNameMovie)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.nameExampleMovie = QtWidgets.QTextBrowser(parent=self.tab_3)
        self.nameExampleMovie.setObjectName("nameExampleMovie")
        self.horizontalLayout_15.addWidget(self.nameExampleMovie)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.nameTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_23 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.mainTitleTV = QtWidgets.QLineEdit(parent=self.tab_4)
        self.mainTitleTV.setObjectName("mainTitleTV")
        self.horizontalLayout_20.addWidget(self.mainTitleTV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_24 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.secondTitleTV = QtWidgets.QLineEdit(parent=self.tab_4)
        self.secondTitleTV.setObjectName("secondTitleTV")
        self.horizontalLayout_21.addWidget(self.secondTitleTV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_25 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_22.addWidget(self.label_25)
        self.fileNameTV = QtWidgets.QLineEdit(parent=self.tab_4)
        self.fileNameTV.setObjectName("fileNameTV")
        self.horizontalLayout_22.addWidget(self.fileNameTV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_26 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_23.addWidget(self.label_26)
        self.nameExampleTV = QtWidgets.QTextBrowser(parent=self.tab_4)
        self.nameExampleTV.setObjectName("nameExampleTV")
        self.horizontalLayout_23.addWidget(self.nameExampleTV)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.nameTabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_19 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_16.addWidget(self.label_19)
        self.mainTitlePlaylet = QtWidgets.QLineEdit(parent=self.tab_5)
        self.mainTitlePlaylet.setObjectName("mainTitlePlaylet")
        self.horizontalLayout_16.addWidget(self.mainTitlePlaylet)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.secondTitlePlaylet = QtWidgets.QLineEdit(parent=self.tab_5)
        self.secondTitlePlaylet.setObjectName("secondTitlePlaylet")
        self.horizontalLayout_17.addWidget(self.secondTitlePlaylet)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_21 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_18.addWidget(self.label_21)
        self.fileNamePlaylet = QtWidgets.QLineEdit(parent=self.tab_5)
        self.fileNamePlaylet.setObjectName("fileNamePlaylet")
        self.horizontalLayout_18.addWidget(self.fileNamePlaylet)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_22 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.nameExamplePlaylet = QtWidgets.QTextBrowser(parent=self.tab_5)
        self.nameExamplePlaylet.setObjectName("nameExamplePlaylet")
        self.horizontalLayout_19.addWidget(self.nameExamplePlaylet)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.nameTabWidget.addTab(self.tab_5, "")
        self.verticalLayout_9.addWidget(self.nameTabWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_28 = QtWidgets.QLabel(parent=self.tab_6)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_25.addWidget(self.label_28)
        self.autoFeedLink = QtWidgets.QTextEdit(parent=self.tab_6)
        self.autoFeedLink.setObjectName("autoFeedLink")
        self.horizontalLayout_25.addWidget(self.autoFeedLink)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_27 = QtWidgets.QLabel(parent=self.tab_6)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_24.addWidget(self.label_27)
        self.autoFeedIllustrate = QtWidgets.QTextBrowser(parent=self.tab_6)
        self.autoFeedIllustrate.setObjectName("autoFeedIllustrate")
        self.horizontalLayout_24.addWidget(self.autoFeedIllustrate)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(2, -1, 2, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_29 = QtWidgets.QLabel(parent=self.tab_6)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_26.addWidget(self.label_29)
        self.openAutoFeedLink = QtWidgets.QCheckBox(parent=self.tab_6)
        self.openAutoFeedLink.setChecked(True)
        self.openAutoFeedLink.setObjectName("openAutoFeedLink")
        self.horizontalLayout_26.addWidget(self.openAutoFeedLink)
        self.label_30 = QtWidgets.QLabel(parent=self.tab_6)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_26.addWidget(self.label_30)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_11.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveButton = QtWidgets.QPushButton(parent=Settings)
        self.saveButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=Settings)
        self.cancelButton.setStyleSheet("QPushButton {\n"
"    display: inline-block;\n"
"    padding: 6px 6px;\n"
"    font-size: 14px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #16bf9d,\n"
"                                      stop:1 #10a266);\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #11b998,\n"
"                                      stop:1 #08965e);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: \n"
"                qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 #0e9278,\n"
"                                      stop:1 #0e925c);\n"
"}\n"
"")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        self.nameTabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "设置"))
        self.label_8.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_8.setText(_translate("Settings", "PT Gen地址:"))
        self.ptGenApiUrl.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_6.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_6.setText(_translate("Settings", "图床API地址:"))
        self.pictureBedApiUrl.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_7.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_7.setText(_translate("Settings", "图床API密钥:"))
        self.pictureBedApiToken.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_3.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_3.setText(_translate("Settings", "截图储存地址:"))
        self.screenshotPath.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.selectScreenshotPathButton.setText(_translate("Settings", "浏览"))
        self.label_12.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_12.setText(_translate("Settings", "种子储存地址:"))
        self.torrentPath.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.selectTorrentPathButton.setText(_translate("Settings", "浏览"))
        self.label.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label.setText(_translate("Settings", "截图数量:"))
        self.screenshotNumber.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_2.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_2.setText(_translate("Settings", "关键帧复杂度:"))
        self.screenshotThreshold.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_4.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_4.setText(_translate("Settings", "截图起始点（百分比）:"))
        self.screenshotStartPercentage.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_5.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_5.setText(_translate("Settings", "截图终止点（百分比）:"))
        self.screenshotEndPercentage.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.autoUploadScreenshot.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.autoUploadScreenshot.setText(_translate("Settings", "自动上传图床"))
        self.pasteScreenshotUrl.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.pasteScreenshotUrl.setText(_translate("Settings", "将链接粘贴到简介后"))
        self.deleteScreenshot.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.deleteScreenshot.setText(_translate("Settings", "上传后删除本地图片"))
        self.mediaInfoSuffix.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.mediaInfoSuffix.setText(_translate("Settings", "MediaInfo工具后缀"))
        self.doGetThumbnail.setText(_translate("Settings", "生成缩略图"))
        self.label_13.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_13.setText(_translate("Settings", "横向数量:"))
        self.thumbnailRows.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_14.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_14.setText(_translate("Settings", "纵向数量:"))
        self.thumbnailCols.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_31.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_31.setText(_translate("Settings", "上传延迟(s):"))
        self.thumbnailDelay.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_10.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_10.setText(_translate("Settings", "获取标准命名时:"))
        self.renameFile.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.renameFile.setText(_translate("Settings", "自动将文件（文件夹）重命名"))
        self.makeDir.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.makeDir.setText(_translate("Settings", "将电影文件放入同名文件夹"))
        self.secondConfirmFileName.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.secondConfirmFileName.setText(_translate("Settings", "二次确认文件名"))
        self.enableApi.setText(_translate("Settings", "启用API功能（更改后需要重启软件生效）"))
        self.label_32.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_32.setText(_translate("Settings", "监听端口（1-65535）:"))
        self.apiPort.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.label_9.setText(_translate("Settings", "说明"))
        self.textBrowser.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">截图数量最多5个，图片越多、视频越高清速度越慢，请耐心等待。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">关键帧复杂度指对画面的要求，数字越大画面越复杂，符合条件的画面也会越少，数量不足会随机截图。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">截图起始点指截图开始的时刻在整个电影长度的占比，不易过小，以免截取片头。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">截图终止点一定要比起始点大，否则无法截图，间隔如果太小也会导致截图数量不足。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果发现生成的缩略图位置不在最后，请适当增大上传延迟。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">对文件夹处理时仅获取其中第一个视频的参数信息，对剧集批量重命名请按文件名排好序。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">制作种子时，如果选中的资源是文件夹，则直接制作；如果是文件，则对上级文件夹制作。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用“一键启动”请取消勾选”二次确认文件名“，耐心等待勿反复点击，Pt-Gen连接性不好时不建议使用。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">文件越大制作种子越慢，可查看任务管理器获取运行情况，资源路径可以直接复制文件粘贴到文本框。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">目前支持的免费图床： <span style=\" color:#0000ff;\">https://freeimage.host/ https://imgbb.com/</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">图床的API地址和密钥请到图床主页获取。</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Settings", "常规"))
        self.label_15.setText(_translate("Settings", "主标题:"))
        self.mainTitleMovie.setText(_translate("Settings", "{en_title} {year} {video_format} {source} {video_codec} {hdr_format} {audio_codec} {channels}-{team}"))
        self.label_17.setText(_translate("Settings", "副标题:"))
        self.secondTitleMovie.setText(_translate("Settings", "{original_title} / {other_title} | {category} | {actors}"))
        self.label_16.setText(_translate("Settings", "文件名:"))
        self.fileNameMovie.setText(_translate("Settings", "{original_title}.{en_title}.{year}.{video_format}.{source}.{video_codec}.{hdr_format}.{audio_codec}.{channels}-{team}"))
        self.label_18.setText(_translate("Settings", "占位符:"))
        self.nameExampleMovie.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{en_title}：英文标题</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{original_tite}：原语言标题（原语言是英文，则使用中文标题）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{year}：发布年份（不包含单位”年“）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_format}： 分辨率</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{source}：资源来源</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_codec}：视频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{bit_depth}：色深</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{hdr_format}：HDR信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{frame_rate}：帧数信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{audio_codec}：音频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{channels}：声道数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{team}：制作组</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{other_titles}：其他译名</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{category}：影片类型</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{actors}：主要演员 </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">注意：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ff0000;\">红色选项</span>可通过修改<span style=\" font-weight:700;\">static/abbreviation.json</span>进行自定义</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#0000ff;\">蓝色选项</span>可通过修改<span style=\" font-weight:700;\">static目录</span>下对应的<span style=\" font-weight:700;\">json文件</span>进行自定义</p></body></html>"))
        self.nameTabWidget.setTabText(self.nameTabWidget.indexOf(self.tab_3), _translate("Settings", "电影"))
        self.label_23.setText(_translate("Settings", "主标题:"))
        self.mainTitleTV.setText(_translate("Settings", "{en_title} {year} {video_format} {source} {video_codec} {hdr_format} {audio_codec} {channels}-{team}"))
        self.label_24.setText(_translate("Settings", "副标题:"))
        self.secondTitleTV.setText(_translate("Settings", "{original_title} / {other_title} | {category} | {actors}"))
        self.label_25.setText(_translate("Settings", "文件名:"))
        self.fileNameTV.setText(_translate("Settings", "{original_title}.{en_title}.{year}.{video_format}.{source}.{video_codec}.{hdr_format}.{audio_codec}.{channels}-{team}"))
        self.label_26.setText(_translate("Settings", "占位符:"))
        self.nameExampleTV.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{en_title}：英文标题</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{original_tite}：原语言标题（原语言是英文，则使用中文标题）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{season}：季（两位，不足补0，用于配合S方便刮削，例如S01、S11）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{episode}：集（两位以上，不足补0，用于配合E方便刮削，例如E01、E11、E111）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{year}：发布年份（不包含单位”年“）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_format}： 分辨率</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{source}：资源来源</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_codec}：视频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{bit_depth}：色深</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{hdr_format}：HDR信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{frame_rate}：帧数信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{audio_codec}：音频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{channels}：声道数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{team}：制作组</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{other_titles}：其他译名</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{season_number}：季数 （不补0，用于副标题：第{season_number}季）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{total_episode}：总集数（格式：全n集/第m-n集，取决于是否开始于第1集）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{category}：影片类型</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{actors}：主要演员 </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">注意：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ff0000;\">红色选项</span>可通过修改<span style=\" font-weight:700;\">static/abbreviation.json</span>进行自定义</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#0000ff;\">蓝色选项</span>可通过修改<span style=\" font-weight:700;\">static目录</span>下对应的<span style=\" font-weight:700;\">json文件</span>进行自定义</p></body></html>"))
        self.nameTabWidget.setTabText(self.nameTabWidget.indexOf(self.tab_4), _translate("Settings", "剧集"))
        self.label_19.setText(_translate("Settings", "主标题:"))
        self.mainTitlePlaylet.setText(_translate("Settings", "{en_title} {year} {video_format} {source} {video_codec} {hdr_format} {audio_codec} {channels}-{team}"))
        self.label_20.setText(_translate("Settings", "副标题:"))
        self.secondTitlePlaylet.setText(_translate("Settings", "{original_title} | 第{season} | {total_episode} | {year}年 | {type} | 类型：{category}"))
        self.label_21.setText(_translate("Settings", "文件名:"))
        self.fileNamePlaylet.setText(_translate("Settings", "{original_title}.{en_title}.{year}.{video_format}.{source}.{video_codec}.{hdr_format}.{audio_codec}.{channels}-{team}"))
        self.label_22.setText(_translate("Settings", "占位符:"))
        self.nameExamplePlaylet.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{en_title}：英文标题</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{original_tite}：原语言标题（原语言是英文，则使用中文标题）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{season}：季（两位，不足补0，用于配合S方便刮削，例如S01、S11）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{episode}：集（两位以上，不足补0，用于配合E方便刮削，例如E01、E11、E111）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{year}：发布年份（不包含单位”年“）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_format}： 分辨率</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{source}：资源来源</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{video_codec}：视频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{bit_depth}：色深</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{hdr_format}：HDR信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{frame_rate}：帧数信息</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{audio_codec}：音频编码</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">{channels}：声道数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{team}：制作组</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{season_number}：季数 （不补0，用于副标题：第{season_number}季）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{total_episode}：总集数（全n集/第m-n集，取决于是否开始于第1集）</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">{type}：短剧收费类型</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">{category}：影片类型 </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">注意：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ff0000;\">红色选项</span>可通过修改<span style=\" font-weight:700;\">static/abbreviation.json</span>进行自定义</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">蓝色选项</span>可通过修改<span style=\" font-weight:700;\">static目录</span>下对应的<span style=\" font-weight:700;\">json文件</span>进行自定义</p></body></html>"))
        self.nameTabWidget.setTabText(self.nameTabWidget.indexOf(self.tab_5), _translate("Settings", "短剧"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Settings", "命名"))
        self.label_28.setText(_translate("Settings", "链接:"))
        self.autoFeedLink.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">https://example.com/upload.php#seperator#name#linkstr#{主标题}#linkstr#small_descr#linkstr#{副标题}#linkstr#url#linkstr#{IMDB}#linkstr#dburl#linkstr{豆瓣}#linkstr#descr#linkstr#{简介}[quote]{MediaInfo}[/quote]#linkstr#log_info#linkstr##linkstr#tracklist#linkstr##linkstr#music_type#linkstr##linkstr#music_media#linkstr##linkstr#edition_info#linkstr##linkstr#music_name#linkstr##linkstr#music_author#linkstr##linkstr#animate_info#linkstr##linkstr#anidb#linkstr##linkstr#torrentName#linkstr##linkstr#images#linkstr##linkstr#torrent_name#linkstr##linkstr#torrent_url#linkstr##linkstr#type#linkstr#{类型}#linkstr#source_sel#linkstr#{地区}#linkstr#standard_sel#linkstr#{分辨率}#linkstr#audiocodec_sel#linkstr#{音频编码}#linkstr#codec_sel#linkstr#{视频编码}#linkstr#medium_sel#linkstr#{媒介}#linkstr#origin_site#linkstr##linkstr#origin_url#linkstr##linkstr#golden_torrent#linkstr#false#linkstr#mediainfo_cmct#linkstr##linkstr#imgs_cmct#linkstr##linkstr#full_mediainfo#linkstr##linkstr#subtitles#linkstr##linkstr#youtube_url#linkstr##linkstr#ptp_poster#linkstr##linkstr#comparisons#linkstr##linkstr#version_info#linkstr##linkstr#multi_mediainfo#linkstr##linkstr#labels#linkstr#100</p></body></html>"))
        self.label_27.setText(_translate("Settings", "说明:"))
        self.autoFeedIllustrate.setHtml(_translate("Settings", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用前请安装最新版本auto_feed：<span style=\" font-weight:700; color:#0000ff;\">https://greasyfork.org/zh-CN/scripts/424132-auto-feed</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">将上方链接最前方域名：<span style=\" font-weight:700; color:#0000ff;\">“example.com”</span>替换为想要发布的站点域名，注意保留<span style=\" font-weight:700; color:#ff0000;\">“upload.php”</span>！！！目前仅支持部分NexusPHP架构并且适配了auto_feed的站点！！！</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">如果不确定怎么用请<span style=\" color:#ff0000;\">不要对除了域名外任何地方做任何修改</span>！！！</p></body></html>"))
        self.openAutoFeedLink.setStyleSheet(_translate("Settings", "QPushButton {\n"
"    display: inline-block;\n"
"    padding: 5px 5px;\n"
"    font-size: 16px;\n"
"    cursor: pointer;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    outline: none;\n"
"    color:#fff;\n"
"    background-color: #559e24;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"    box-shadow: 0 9px #999;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #4a8821;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3c6f1b;\n"
"}\n"
""))
        self.openAutoFeedLink.setText(_translate("Settings", "获取auto feed链接后自动打开链接（默认浏览器需安装auto feed脚本）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Settings", "上传"))
        self.saveButton.setText(_translate("Settings", "保存"))
        self.cancelButton.setText(_translate("Settings", "取消"))
